available_ip:
  - class: Accumulator
  - class: AxiCdma
  - class: AxiHwicap
    max: 1
  - class: AxiTimer
  - class: Dft
  - class: Emc
  - class: Gpio
  - class: Microblaze
  - class: Uartlite
  - class: XadcWiz
    max: 1


min_ip: 2
max_ip: 18

